##  Common Matrix Operations 

In [1]:
import numpy as np

In [4]:
#make matrix 
m=[[1,2,3],
   [4,5,6],
   [7,8,9]]

matrix=np.array(m)

In [25]:
#eigen value
eigen_vals,eigen_vecs=np.linalg.eig(matrix)
print("Eigen Values\n",eigen_vals)
print("Eigen Vectors\n",eigen_vecs)

Eigen Values
 [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
Eigen Vectors
 [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [35]:
#transpose
trans=np.matrix.transpose(matrix)
print("Transpose\n",trans)

Transpose
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [34]:
#inverse
inverse=np.linalg.inv(matrix)

LinAlgError: Singular matrix

#### Singular Matrix gives an error as it has a zero determinant

In [37]:
det_value=np.linalg.det(matrix)
print (det_value)

0.0


#### Lets determine another matrix

In [38]:
matrix_2=[[3,2,1],[2,2,1],[1,1,4]]
matrix_2=np.matrix(matrix_2)

In [41]:
print(np.linalg.det(matrix_2))

7.000000000000001


#### Non-Zero Determinant !!!
#### So we can go for inverse

In [43]:
inverse=np.linalg.inv(matrix_2)
print(inverse)

[[ 1.         -1.          0.        ]
 [-1.          1.57142857 -0.14285714]
 [ 0.         -0.14285714  0.28571429]]
